# Generated by Django 2.1 on 2018-08-15 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', help_text='关键词', max_length=30, verbose_name='关键词')),
                ('desc', models.TextField(default='', help_text='回复信息', verbose_name='回复信息')),
                ('add_time', models.DateTimeField(default=datetime.datetime, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '关键词信息',
                'verbose_name_plural': '关键词信息',
            },
        ),
    ]
