# Generated by Django 2.1 on 2018-08-15 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='add_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='添加时间'),
        ),
    ]
