# Generated by Django 2.1 on 2018-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0002_auto_20180815_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='add_time',
            field=models.DateTimeField(default='2018-08-15 08:01:40.750032', verbose_name='添加时间'),
        ),
    ]
