# Generated by Django 2.1 on 2018-08-15 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robot_app', '0004_auto_20180815_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
